databases:
  - name: anigram
    databaseName: anigram
    user: anigram

services:
  - type: web
    name: anigram
    env: python
    buildCommand: "_scripts/build.sh"
    startCommand: "gunicorn anigram.wsgi"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: anigram
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
