# Generated by Django 4.1.1 on 2022-09-05 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_clients_userid_clients_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
