# Generated by Django 3.2.15 on 2022-10-21 12:56

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image_url', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image_url')),
                ('username', models.CharField(max_length=100)),
            ],
        ),
    ]
