# Generated by Django 4.1 on 2022-09-01 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lead',
            new_name='Post',
        ),
    ]
