# Generated by Django 4.1 on 2022-09-03 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='owner',
        ),
    ]
