# Generated by Django 4.1.1 on 2022-09-07 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verified_breeder',
            field=models.CharField(default='No', max_length=10),
        ),
    ]
