# Generated by Django 4.1.1 on 2022-09-07 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='status',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='verified_breeder',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='credentials',
            field=models.CharField(default='', max_length=500),
        ),
    ]
