# Generated by Django 4.1.1 on 2022-09-07 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofile_status_userprofile_verified_breeder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='verified_breeder',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(default='', max_length=50),
        ),
    ]
