databases:
  - name: anigram
    databaseName: mysite
    user: anigram

services:
  - type: web
    name: anigram
    env: python
    buildCommand: "_scripts/build.sh"
    startCommand: ALLOWED_HOSTS=".onrender.com" "gunicorn anigram.wsgi"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysite
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
